#!/usr/bin/env node
import { readFileSync, writeFileSync, rmSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const RUN_NAMES = [
  "amber", "atoll", "basalt", "blitz", "cipher",
  "citrine", "comet", "coral", "cosmo", "crimson",
  "diamond", "draco", "drift", "dune", "echo",
  "ember", "emerald", "fjord", "flux", "garnet",
  "geode", "glyph", "havoc", "indigo", "islet",
  "jade", "knoll", "lunar", "nebula", "nova",
  "ochre", "onyx", "opal", "orion", "pulsar",
  "rigel", "ruby", "sable", "sol", "teal",
  "topaz", "vega", "violet", "wisp", "zenith",
];

const runsPath = resolve(root, "data/runs.json");
const runs = JSON.parse(readFileSync(runsPath, "utf-8"));
const currentIds = runs.map((r) => r.id).sort();

if (currentIds.length > RUN_NAMES.length) {
  console.error(`Need ${currentIds.length} names but only have ${RUN_NAMES.length}`);
  process.exit(1);
}

const idMap = {};
for (let i = 0; i < currentIds.length; i++) {
  idMap[currentIds[i]] = RUN_NAMES[i];
}

console.log(`Mapping ${currentIds.length} run IDs:`);
for (const [oldId, newId] of Object.entries(idMap)) {
  console.log(`  ${oldId} → ${newId}`);
}

// Update runs.json
for (const run of runs) {
  if (idMap[run.id]) run.id = idMap[run.id];
}
writeFileSync(runsPath, JSON.stringify(runs, null, 2) + "\n");
console.log(`\n✓ Updated runs.json`);

// Update test-results.json (keys)
const trPath = resolve(root, "data/test-results.json");
const tr = JSON.parse(readFileSync(trPath, "utf-8"));
const newTr = {};
for (const [key, value] of Object.entries(tr)) {
  newTr[idMap[key] ?? key] = value;
}
writeFileSync(trPath, JSON.stringify(newTr, null, 2) + "\n");
console.log(`✓ Updated test-results.json`);

// Update promotions.json (runId fields)
const promosPath = resolve(root, "data/promotions.json");
const promos = JSON.parse(readFileSync(promosPath, "utf-8"));
for (const p of promos) {
  if (idMap[p.runId]) p.runId = idMap[p.runId];
}
writeFileSync(promosPath, JSON.stringify(promos, null, 2) + "\n");
console.log(`✓ Updated promotions.json`);

// Remove stale per-run files (will be regenerated by split script)
const publicDir = resolve(root, "public/data/test-results");
if (existsSync(publicDir)) {
  rmSync(publicDir, { recursive: true, force: true });
  console.log(`✓ Removed stale ${publicDir}`);
}

console.log("\nDone. Run `node scripts/split-test-results.mjs` to regenerate public/ files.");
