import React from "react";
import { FileText, CheckCircle2, AlertTriangle, AlertCircle, GitBranch } from "lucide-react";
import { getTestCaseById } from "@/lib/data";
import { DIFF_ROWS } from "@/lib/runs";
import type { TestCase } from "@/lib/types";

function RelatedTests({ testCase }: { testCase: TestCase }) {
  const relatedIds = testCase.relatedTestIds ?? [];
  const related = relatedIds
    .map(id => ({ tc: getTestCaseById(id), diff: DIFF_ROWS.find(d => d.id === id) }))
    .filter(x => x.tc || x.diff);

  if (related.length === 0) {
    return (
      <div style={{ padding: 20, textAlign: "center", fontSize: 12, color: "var(--gcp-text-secondary)" }}>
        No related tests
      </div>
    );
  }

  return (
    <div style={{ padding: 0 }}>
      <table className="gcp-table" style={{ width: "100%" }}>
        <tbody>
          {related.map(rel => {
            const name = rel.tc?.name ?? rel.diff?.name ?? rel.diff?.id ?? "";
            const status = rel.diff?.candStatus ?? rel.tc?.status ?? "SKIP";
            const isFail = status === "FAIL" || status === "deprecated";
            return (
              <tr key={rel.tc?.id ?? rel.diff?.id} style={{ cursor: "pointer", background: isFail ? "var(--gcp-red-bg)" : "transparent" }}>
                <td style={{ padding: "10px 12px" }}>
                  <div style={{ fontFamily: "var(--font-mono)", fontSize: 12, overflow: "hidden", textOverflow: "ellipsis", maxWidth: 200, whiteSpace: "nowrap" }} title={name}>{name}</div>
                </td>
                <td style={{ padding: "10px 12px", textAlign: "right" }}>
                  <span className={`gcp-badge ${isFail ? "gcp-badge-fail" : "gcp-badge-pass"}`} style={{ fontSize: 10 }}>{status}</span>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

export function TestDocSidebar({ testCase }: { testCase?: TestCase }) {
  const tags = testCase?.tags ?? [];
  const predicates = testCase?.predicates ?? [];
  const preconditions = testCase?.preconditions ?? "";
  const precondLines = preconditions ? preconditions.split("\n").filter(l => l.trim()) : [];

  return (
    <div style={{ width: "100%", display: "flex", flexDirection: "column", gap: 16, overflowY: "auto", paddingRight: 8, paddingBottom: 32, height: "calc(100vh - 150px)" }}>
      {testCase?.documentation && (
        <div className="gcp-card" style={{ padding: 16 }}>
          <div style={{ fontSize: 10, fontWeight: 700, color: "var(--gcp-text-secondary)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 6 }}>
            <FileText size={12} style={{ marginRight: 4, display: "inline", verticalAlign: "middle" }} />
            Auto-generated Documentation
          </div>
          <div style={{ fontSize: 11, lineHeight: 1.6, whiteSpace: "pre-wrap", color: "var(--gcp-text)", background: "var(--gcp-grey-bg)", padding: 12, borderRadius: 6, maxHeight: 400, overflowY: "auto" }}>
            {testCase.documentation}
          </div>
          {testCase.documentation.toLowerCase().includes("auto-generated") && (
            <div style={{ fontSize: 10, color: "var(--gcp-text-secondary)", marginTop: 4, fontStyle: "italic" }}>
              Auto-generated by AI on first creation
            </div>
          )}
        </div>
      )}
      <div className="gcp-card" style={{ display: "flex", flexDirection: "column" }}>
        <div style={{ padding: "12px 16px", borderBottom: "1px solid var(--gcp-grey)", background: "var(--gcp-surface-hover)" }}>
          <h2 style={{ fontWeight: 500, display: "flex", alignItems: "center", gap: 8 }}>
            <FileText size={18} style={{ color: "var(--gcp-blue)" }} />
            Test Documentation
          </h2>
        </div>
        <div style={{ padding: 20, display: "flex", flexDirection: "column", gap: 24 }}>
          <div>
            {testCase?.description ? (
              <p style={{ fontSize: 13, lineHeight: 1.6, marginBottom: 12 }}>{testCase.description}</p>
            ) : (
              <p style={{ fontSize: 13, lineHeight: 1.6, marginBottom: 12, color: "var(--gcp-text-secondary)", fontStyle: "italic" }}>No description</p>
            )}
            {tags.length > 0 && (
              <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                {tags.map(tag => (
                  <span key={tag} style={{ fontSize: 11, padding: "2px 8px", borderRadius: 12, background: "var(--gcp-blue-bg)", color: "var(--gcp-blue)", border: "1px solid var(--gcp-blue)", fontWeight: 500 }}>#{tag}</span>
                ))}
              </div>
            )}
          </div>

          {predicates.length > 0 && (
            <div>
              <h3 style={{ fontSize: 11, fontWeight: 700, color: "var(--gcp-text-secondary)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 8 }}>Validates</h3>
              <ul style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                {predicates.map(p => (
                  <li key={p.id} style={{ display: "flex", alignItems: "flex-start", gap: 8, fontSize: 13 }}>
                    <CheckCircle2 size={16} style={{ color: "var(--gcp-green)", flexShrink: 0, marginTop: 2 }} />
                    <span style={{ fontFamily: "var(--font-mono)", fontSize: 13 }}>{p.description || `${p.field} ${p.operator} ${p.expected}`}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {precondLines.length > 0 && (
            <div style={{ background: "var(--gcp-yellow-bg)", padding: 12, borderRadius: 6, border: "1px solid var(--gcp-yellow)" }}>
              <h3 style={{ fontSize: 11, fontWeight: 700, color: "var(--gcp-yellow)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 8, display: "flex", alignItems: "center", gap: 4 }}>
                <AlertTriangle size={14} /> Preconditions
              </h3>
              <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 4, fontSize: 13, color: "var(--gcp-text)", listStyle: "disc" }}>
                {precondLines.map((line, i) => <li key={i}>{line}</li>)}
              </ul>
            </div>
          )}

          <div style={{ background: "var(--gcp-red-bg)", padding: 12, borderRadius: 6, border: "1px solid var(--gcp-red)" }}>
            <h3 style={{ fontSize: 11, fontWeight: 700, color: "var(--gcp-red)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 8, display: "flex", alignItems: "center", gap: 4 }}>
              <AlertCircle size={14} /> Known Flakiness
            </h3>
            <div style={{ fontSize: 13 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                <span style={{ fontWeight: 500 }}>Flake rate:</span>
                <span style={{ fontFamily: "var(--font-mono)", color: "var(--gcp-red)", fontWeight: 700 }}>N/A</span>
                <span style={{ fontSize: 12, color: "var(--gcp-text-secondary)" }}>(last 90d)</span>
              </div>
              <p style={{ fontSize: 13, color: "var(--gcp-text-secondary)", marginTop: 4 }}>
                Tracked per-run in test history
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="gcp-card" style={{ display: "flex", flexDirection: "column" }}>
        <div style={{ padding: 12, borderBottom: "1px solid var(--gcp-grey)", background: "var(--gcp-surface-hover)" }}>
          <h2 style={{ fontWeight: 500, fontSize: 13, display: "flex", alignItems: "center", gap: 8 }}>
            <GitBranch size={16} style={{ color: "var(--gcp-text-secondary)" }} />
            Related Tests
          </h2>
        </div>
        {testCase ? <RelatedTests testCase={testCase} /> : null}
      </div>
    </div>
  );
}
