// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aware/About.tsx": () => import("../components/mockups/aware/About.tsx"),
  "./components/mockups/aware/Compare.tsx": () => import("../components/mockups/aware/Compare.tsx"),
  "./components/mockups/aware/Dashboard.tsx": () => import("../components/mockups/aware/Dashboard.tsx"),
  "./components/mockups/aware/RunDetail.tsx": () => import("../components/mockups/aware/RunDetail.tsx"),
  "./components/mockups/aware/Runs.tsx": () => import("../components/mockups/aware/Runs.tsx"),
  "./components/mockups/aware/SearchDemo.tsx": () => import("../components/mockups/aware/SearchDemo.tsx"),
  "./components/mockups/aware/Sharing.tsx": () => import("../components/mockups/aware/Sharing.tsx"),
  "./components/mockups/aware/StartRun.tsx": () => import("../components/mockups/aware/StartRun.tsx"),
  "./components/mockups/aware/Status.tsx": () => import("../components/mockups/aware/Status.tsx"),
  "./components/mockups/aware/TestAnalytics.tsx": () => import("../components/mockups/aware/TestAnalytics.tsx"),
  "./components/mockups/aware/TestDoc.tsx": () => import("../components/mockups/aware/TestDoc.tsx"),
  "./components/mockups/aware/TestManager.tsx": () => import("../components/mockups/aware/TestManager.tsx"),
  "./components/mockups/aware/TestSuiteManager.tsx": () => import("../components/mockups/aware/TestSuiteManager.tsx")
};
