import type { CiConfigOutput, TestSuite } from '@/lib/types';
import { getTestSuites, getTestCases } from '@/lib/data';
import { getEnvConfigs } from '@/lib/envConfig';

export function generateCiConfig(): CiConfigOutput {
  const suites = getTestSuites();
  const tests = getTestCases();
  const envs = getEnvConfigs();

  return {
    version: '3.0',
    project: 'A.W.A.R.E. — Akamai Web Analytics Regression Engine',
    suites: suites.map(s => {
      const suiteTests = tests.filter(t => s.testIds.includes(t.id));
      const runners = new Set<string>();
      const categories = new Set<string>();
      for (const t of suiteTests) {
        if (t.testType === 'web') runners.add('playwright');
        else if (t.testType === 'pytest') runners.add('pytest');
        if (t.category) categories.add(t.category);
      }
      return {
        name: s.name,
        testCount: suiteTests.length,
        runners: [...runners],
        categories: [...categories],
      };
    }),
    environments: envs.map(e => ({
      id: e.id,
      label: e.label,
      target: e.target,
      network: e.network,
      ...(e.ips.length > 0 ? { ips: e.ips } : {}),
    })),
    workflow: {
      file: 'controller.yml',
      path: '.github/workflows/controller.yml',
    },
    runners: {
      playwright: { browser: 'chromium' },
      pytest: { markers: ['smoke', 'regression'] },
    },
    instructions: 'Promotion gate requires 95% pass rate before PROD activation.',
  };
}

export function generateCiConfigYaml(options?: {
  suite: string;
  environment: string;
  runner?: 'playwright' | 'puppeteer' | 'http';
  timeout?: number;
  retries?: number;
  parallel?: number;
}): string {
  if (options) {
    const { suite, environment, runner = 'playwright', timeout = 300, retries = 2, parallel = 4 } = options;
    return `# A.W.A.R.E. CI Configuration
# Auto-generated — do not edit manually

suite: ${suite}
environment: ${environment}
runner: ${runner}
settings:
  timeout: ${timeout}
  retries: ${retries}
  parallel: ${parallel}
  screenshotOnFailure: true
  traceOnRetry: true

reporting:
  notifyOnFailure: true
  uploadArtifacts: true
  badge: https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/ruake/AWARE/data/badge.json
`;
  }
  const cfg = generateCiConfig();
  const lines: string[] = ['# CI Config generated by A.W.A.R.E.', `version: "${cfg.version}"`, `project: "${cfg.project}"`, ''];
  lines.push('suites:');
  for (const s of cfg.suites) {
    lines.push(`  - name: "${s.name}"`);
    lines.push(`    testCount: ${s.testCount}`);
  }
  return lines.join('\n');
}

export function downloadCiConfig(filename?: string, content?: string): void {
  const yaml = content ?? generateCiConfigYaml();
  const resolvedFilename = filename ?? 'ci-config.yml';
  const blob = new Blob([yaml], { type: 'text/yaml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = resolvedFilename.endsWith('.yml') ? resolvedFilename : `${resolvedFilename}.yml`;
  if (document.body) {
    document.body.appendChild(a);
  }
  a.click();
  if (document.body) {
    document.body.removeChild(a);
  }
  URL.revokeObjectURL(url);
}
